### ISSUE TITLE
Issue with JS and React-Native

### ISSUE THREAD

**Issue by Freddy03h** [MoOx/react-from-svg#13]
I found an issue that only happen on a react-native project with js output : `--with-native`

There is space between elements so it raise an error : `Error: Text strings must be rendered within a <Text> component`

```js
 stroke={stroke}> <Path d="M8.388
```

```js
8.388z"/> </Svg>
```

No issue on ReasonReactNative because JSX isn't the same.

**Comment by MoOx** [comment]
This thing https://github.com/MoOx/react-from-svg/blob/ad22c3d77527bb86fe7b020e800d9a75f5574a08/src/AdjustSvg.re#L56 should probably just be called for reason

**Comment by MoOx** [comment]
Closed by #14
