### ISSUE TITLE
Issue with minified svg

### ISSUE THREAD

**Issue by Freddy03h** [MoOx/react-from-svg#9]
Minified SVG (one line) have issues.

Example:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M336 192h40a40 40 0 0140 40v192a40 40 0 01-40 40H136a40 40 0 01-40-40V232a40 40 0 0140-40h40M336 128l-80-80-80 80M256 321V48" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/></svg>
```
will produce:
```jsx
<Svg viewBox="0 0 512 512" width={width} height={height} fill={fill} stroke={stroke}><Path d="M336 192h40a40 40 0 0140 40v192a40 40 0 01-40 40H136a40 40 0 01-40-40V232a40 40 0 0140-40h40M336 128l-80-80-80 80M256 321V48"  stroke="#000" strokeLinecap="round" strokeLinejoin="round" stroke-/></Svg>
```

The `fill` attribute from the `<Path>` element is missing (I didn't use `--remove-fill`) and the last attribute isn't transformed well `stroke-`.

It doesn't happen on a well indented svg file.

(my workaround: use `--pretty` on `svgo` before using `react-from-svg`)

**Comment by MoOx** [comment]
There is already some one line svg. I just added test in the codebase & will run some test with this one.

**Comment by MoOx** [comment]
Ok found the issue, working on a fix :)
